==== 說明

一般來說，最好能重複使用single object 去替代 重新建立一個新的相同物件。

作為一個極端的反面例子，看看下面的例子

[source,java]
----

String s = new String("bikini"); //Don't Do This

----

該語法會在每次被執行的時候都會創建一個新的String instance，但是這些創建對象的動作全都是不必要的


[source,java]
----

String s = "bikini";

----

以上的方法只用了一個String instance，而不是每次執行的時候都創建一個新的instance，而且他可以保證，對於所有在同一台VM中的程式碼，只要它們使用了相同的字串都會被重複利用

有些物件創建的成本比其他物件要高得多。如果重複的需要這類"昂貴的物件"，建議將它進行緩存以重複使用。

以下面一個為例子

[source,java]
----
public class StringRomanNumeral {

  public static boolean isRomanNumeral(String s) {
    return s.matches("^(?=.)M*(C[MD]|D?C{0,3})"
        + "(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$");
  }
}
----

**雖然String.matches方法最易於查看一個String是否與正則表達式相符，但並不適合在注重性能的情形中重複使用**

問題在於它在內部為正則表達式創建了一個Pattern instance，卻只使用了一次，之後就進行到 garbage collection內了。

為提高性能，應該將正則表達式編譯成一個Pattern instance，讓它成為類別初始化的一部分，並將她緩存，每當調用isRomanNumeral方法的時候就重用一個instance

[source,java]
----
public class StringRomanNumeral2 {

  private static final Pattern ROMAN = Pattern.compile("^(?=.)M*(C[MD]|D?C{0,3})"
      + "(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$");

  public static boolean isRomanNumeral(String s) {
    return ROMAN.matcher(s).matches();
  }

}
----

改成上面的例子後，除了會加快速度以外，也讓程式碼較為清晰，將原本不可見的Pattern instance做成 final static ，也起了個名字，這樣會比正則表達式本身更有可讀性


另外一個創建多於物件的方法，叫做autoboxing，他允許程式設計師將基本類型和裝箱基本類型(Boxed Primitive Type)混用，且按照需求自動包裝或拆箱。

**autoboxing 使得 Primitive Type和 Boxed Primitive Type之間的差別變得模糊起來，但是並沒有完全消除**

它們在語意上還有著微妙的差別，在性能上也有差異


[source,java]
----

import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.time.StopWatch;

public class PrimitiveTypeDifferent {

  public static void main(String[] args) {
    StopWatch stopWatch=StopWatch.createStarted();
    Long sum = 0L;
    for (long i = 0; i < Integer.MAX_VALUE; i++) {
      sum += i;
    }
    System.out.println(sum);
    System.out.println("step1:"+stopWatch.getTime(TimeUnit.MILLISECONDS));
    stopWatch.reset();

    stopWatch.start();
    long sum2 = 0L;
    for (long i = 0; i < Integer.MAX_VALUE; i++) {
      sum2 += i;
    }
    System.out.println(sum2);
    System.out.println("step2:"+stopWatch.getTime(TimeUnit.MILLISECONDS));

    stopWatch.reset();
    stopWatch.start();
    Long sum3 = 0L;
    for (Long i = 0L; i < Integer.MAX_VALUE; i++) {
      sum3 += i;
    }
    System.out.println(sum3);
    System.out.println("step3:"+stopWatch.getTime(TimeUnit.MILLISECONDS));

    stopWatch.reset();
    stopWatch.start();
    long sum4 = 0L;
    for (Long i = 0L; i < Integer.MAX_VALUE; i++) {
      sum4 += i;
    }
    System.out.println(sum4);
    System.out.println("step4:"+stopWatch.getTime(TimeUnit.MILLISECONDS));
  }

}

----

