==== 說明

請先看以下例子

[source,java]
----
public class Stack {

  private Object[] elements;
  private int size = 0;
  private static final int DEFAULT_INITIAL_CAPACITY = 16;

  public Stack() {
    elements = new Object[DEFAULT_INITIAL_CAPACITY];
  }

  public void push(Object e) {
    ensureCapacity();
    elements[size++] = e;
  }

  public Object pop() {
    if (size == 0) {
      throw new EmptyStackException();
    }
    return elements[--size];
  }

  private void ensureCapacity() {
    if (elements.length == size) {
      elements = Arrays.copyOf(elements, 2 * size + 1);
    }
  }

}
----

===== 第一種問題

在以上的程式碼中，看起來並沒有很明顯的錯誤，無論如何測試，他都會通過測驗，但是這段程式碼卻有一個很嚴重的問題，那就是他會造成memory leak，主要是在pop這個method內當使用了pop這個方法後，會返回elements[--size]的物件，但是該陣列卻還是沒有解除reference，造成了obsolete reference的問題，其改善方法建議為

[source,java]
----
  public Object pop() {
    if (size == 0) {
      throw new EmptyStackException();
    }
    Object result = elements[--size];
    elements[size] = null; //Eliminate obsolete reference
    return result;
  }
----

當程序員第一次被這個問題困擾時，可能會讓你寫程式過度小心，對於每一個對象引用，只要沒用到它，就指到null，其實沒有必要這樣，**清空對象引用 是一種例外 而不是一種規範**，消除過期引用最好的方法，是讓包含該引用的變量結束它的生命週期，如果一直將局部變量的作用域最小化，那就自然而然地會發生


====== 何謂例外

既然都說了清空對象引用應該要是例外 那應該要在什麼情況下清空對象引用呢

我們來仔細研究一下這個Stack

這個Stack類別 一開始先分配好空間 然後棧的0~size-1的element是有在使用的空間 size~elements.length的是沒在使用的空間

天知地知你知我知 但是垃圾回收器不知 對垃圾回收器來說 所有elements的元素都是有在使用的 所以如果你需要垃圾回收器幫你回收 你就要設成null

結論就是 **只要這個類別是自己管理內存 程序員就應該警惕內存泄露問題**


===== 第二種問題

內存泄露的第二個常見原因 是cache

一但你把對象引用放進緩存 他就很容易被遺忘 然後就一直存在緩存裡面很久


===== 第三種問題

監聽器(listener)跟回調(callback)

當你提供了一個API給你的客戶去註冊call back(也就是你的API結束之後去呼叫你的客戶) 客戶很常在已經不需要你回調的時候忘記取消註冊

對於這些情況 一個好的解決方式 是保存這些對象引用的弱引用



==== 結論

由於內存泄露通常不會表現成明顯的失敗 所以他們會一直存在一個系統多年 如果你第一時間沒有查覺 就可能在多年之後發現性能變慢了 才借助Heap剖析工具(Heap Profiler)除錯